apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: $GRAFANA_DATA_HOST
    database: $GRAFANA_DB
    user: $GRAFANA_USER
    editable: $GRAFANA_DATASOURCE_EDITABLE
    idDefault: $GRAFANA_ID_DEFAULT
    secureJsonData:
      password: $GRAFANA_PSW
    jsonData:
      sslmode: $GRAFANA_SSL_MODE
      maxOpenConns: $GRAFANA_MAX_OPEN_CONNS
      maxIdleConns: $GRAFANA_MAX_IDLE_CONNS
      connMaxLifetime: $GRAFANA_CONN_MAX_LIFETIME
      postgresVersion: $GRAFANA_POSTGRES_VERSION
      timescaledb: $GRAFANA_TIMESCALEDB