apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: $GRAFANA_DATA_HOST
    database: $GRAFANA_DB
    user: $GRAFANA_USER
    editable: $GRAFANA_DATASOURCE_EDITABLE
    idDefault: $GRAFANA_ID_DEFAULT
    secureJsonData:
      password: $GRAFANA_PSW
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1000 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: true
    version: 1
    editable: true